# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json

import pytest

from oort_sdk_client.models.send_file_response import SendFileResponse

class TestSendFileResponse:
    """SendFileResponse unit test stubs"""

    @pytest.fixture
    def example_json(self):
        """
        See SendFileResponse x-example-json in the API spec
        """
        example_json = """
        {
  "UUID": "b071ca24-29a5-11f1-9d99-00155d2f52cc"
}

        """
        return example_json

    def test_SendFileResponse(self, example_json):

        # Verify loading from json works
        instance = SendFileResponse.from_json(example_json)

        # It's hard to guarantee that json parsing and dumping preserves string
        # formatting, so compare the objects semantically
        assert json.loads(instance.to_json()) == json.loads(example_json)

