# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json

import pytest

from oort_sdk_client.models.send_options import SendOptions

class TestSendOptions:
    """SendOptions unit test stubs"""

    @pytest.fixture
    def example_json(self):
        """
        See SendOptions x-example-json in the API spec
        """
        example_json = """
        {
  "TTLParams": {
    "urgent": 100,
    "bulk": 200,
    "surplus": 300
  },
  "reliable": true,
  "tags": {
    "foo": "bar",
    "thud": "quux"
  },
  "delivery_hints": {
    "dest_path": "/foo/bar",
    "mode": "640",
    "an": "additionalProperty"
  }
}

        """
        return example_json

    def test_SendOptions(self, example_json):

        # Verify loading from json works
        instance = SendOptions.from_json(example_json)

        # It's hard to guarantee that json parsing and dumping preserves string
        # formatting, so compare the objects semantically
        assert json.loads(instance.to_json()) == json.loads(example_json)

