# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json

import pytest

from oort_sdk_client.models.adcs_xyz_float_t import AdcsXyzFloatT

class TestAdcsXyzFloatT:
    """AdcsXyzFloatT unit test stubs"""

    def test_AdcsXyzFloatT(self):
        pytest.skip("No x-example-json for AdcsXyzFloatT in the API spec")

