# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

# API fixture: test/conftest.py provides sdk_api_client (shared api_client).


# Skip by default unless user enables API testing
pytestmark = pytest.mark.skip(reason="Requires live API or mocking")



def test_command_adcs(sdk_api_client):
    """
    
    POST /adcs
    """

    # --- Arrange ---
    # Required parameters
    adcs_command_request = None  # TODO: provide valid value

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.command_adcs(
            adcs_command_request=adcs_command_request,
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



def test_get_adcs(sdk_api_client):
    """
    
    GET /adcs
    """

    # --- Arrange ---
    # Required parameters

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.get_adcs(
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



def test_get_tfrs(sdk_api_client):
    """
    
    GET /tfrs
    """

    # --- Arrange ---
    # Required parameters

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.get_tfrs(
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



def test_query_available_files(sdk_api_client):
    """
    
    GET /query_available_files/{topic}
    """

    # --- Arrange ---
    # Required parameters
    topic = None  # TODO: provide valid value

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.query_available_files(
            topic=topic,
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



def test_retrieve_file(sdk_api_client):
    """
    
    POST /retrieve_file
    """

    # --- Arrange ---
    # Required parameters
    retrieve_file_request = None  # TODO: provide valid value

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.retrieve_file(
            retrieve_file_request=retrieve_file_request,
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



def test_send_file(sdk_api_client):
    """
    
    POST /send_file
    """

    # --- Arrange ---
    # Required parameters
    send_file_request = None  # TODO: provide valid value

    # Optional parameters

    # --- Act ---
    try:
        response = sdk_api_client.send_file(
            send_file_request=send_file_request,
        )
    except Exception:
        pytest.skip("Call failed (likely due to missing server or params)")

    # --- Assert ---
    assert response is not None



