# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json

import pytest

from oort_sdk_client.models.error_response import ErrorResponse

class TestErrorResponse:
    """ErrorResponse unit test stubs"""

    @pytest.fixture
    def example_json(self):
        """
        See ErrorResponse x-example-json in the API spec
        """
        example_json = """
        {
  "status": 500,
  "message": "yikes"
}

        """
        return example_json

    def test_ErrorResponse(self, example_json):

        # Verify loading from json works
        instance = ErrorResponse.from_json(example_json)

        # It's hard to guarantee that json parsing and dumping preserves string
        # formatting, so compare the objects semantically
        assert json.loads(instance.to_json()) == json.loads(example_json)

