# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json

import pytest

from oort_sdk_client.models.adcs_hk import AdcsHk

class TestAdcsHk:
    """AdcsHk unit test stubs"""

    def test_AdcsHk(self):
        pytest.skip("No x-example-json for AdcsHk in the API spec")

