"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "oort-sdk-client"
VERSION = "1.5.8"
PYTHON_REQUIRES = ">=3.10"
REQUIRES = [
 "urllib3 >= 2.1.0, < 3.0.0",
 "python-dateutil >= 2.8.2",
 "pydantic >= 2.11",
 "typing-extensions >= 4.7.1",
]

setup(
 name=NAME,
 version=VERSION,
 python_requires=PYTHON_REQUIRES,
 description="OORT Agent SDK Interface",
 author="Spire Global, Inc.",
 author_email="team@openapitools.org",
 url="",
 keywords=["OpenAPI", "OpenAPI-Generator", "OORT Agent SDK Interface"],
 install_requires=REQUIRES,
 packages=find_packages(exclude=["test", "tests"]),
 include_package_data=True,
 long_description_content_type='text/markdown',
 long_description="""\
 Client interface to the OORT agent.
 """, # noqa: E501
 package_data={"oort_sdk_client": ["py.typed"]},
)
