# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from oort_sdk_client.models.adcs_quat_t import AdcsQuatT
from oort_sdk_client.models.adcs_target import AdcsTarget
from oort_sdk_client.models.adcs_xyz_float_t import AdcsXyzFloatT
from typing import Optional, Set
from typing_extensions import Self

class AdcsCommandRequest(BaseModel):
    """
    Request to set ADCS mode and parameters
    """ # noqa: E501
    command: Annotated[str, Field(strict=True, max_length=5)] = Field(description="SPACS attitude control command")
    aperture: Optional[Annotated[str, Field(strict=True, max_length=24)]] = Field(default=None, description="Aperture (imager, antenna, etc) name to use in ADCS pointing requests")
    target: Optional[AdcsTarget] = None
    angle: Optional[Union[StrictFloat, StrictInt]] = None
    vector: Optional[AdcsXyzFloatT] = None
    quat: Optional[AdcsQuatT] = None
    __properties: ClassVar[List[str]] = ["command", "aperture", "target", "angle", "vector", "quat"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdcsCommandRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vector
        if self.vector:
            _dict['vector'] = self.vector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quat
        if self.quat:
            _dict['quat'] = self.quat.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdcsCommandRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command": obj.get("command"),
            "aperture": obj.get("aperture"),
            "target": AdcsTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "angle": obj.get("angle"),
            "vector": AdcsXyzFloatT.from_dict(obj["vector"]) if obj.get("vector") is not None else None,
            "quat": AdcsQuatT.from_dict(obj["quat"]) if obj.get("quat") is not None else None
        })
        return _obj


