# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from oort_sdk_client.models.adcs_euler_t import AdcsEulerT
from oort_sdk_client.models.adcs_quat_t import AdcsQuatT
from oort_sdk_client.models.adcs_xyz_float_t import AdcsXyzFloatT
from typing import Optional, Set
from typing_extensions import Self

class AdcsHk(BaseModel):
    """
    ADCS hk response
    """ # noqa: E501
    control_error_angle_deg: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Absolute control error angle ")
    acs_mode_active: Optional[StrictStr] = Field(default=None, description="Active ADCS mode ")
    euler_angles: Optional[AdcsEulerT] = None
    control_error_q: Optional[AdcsQuatT] = None
    lat_deg: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Subsatellite latitude, in degrees ")
    q_bo_est: Optional[AdcsQuatT] = None
    latlontrack_lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="latitude used for ground target tracking ")
    lease_active: Optional[StrictInt] = Field(default=None, description="Flag if a lease is currently active ")
    lon_deg: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Subsatellite longitude, in degrees ")
    eclipse_flag: Optional[StrictInt] = Field(default=None, description="Sunlit/eclipse status of spacecraft ")
    q_bi_est: Optional[AdcsQuatT] = None
    latlontrack_lon: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="longitude used for ground target tracking ")
    r_eci: Optional[AdcsXyzFloatT] = None
    altitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Estimated altitude of satellite in meters ")
    latlontrack_body_vector: Optional[AdcsXyzFloatT] = None
    omega_bo_est: Optional[AdcsXyzFloatT] = None
    acs_mode_cmd: Optional[StrictStr] = Field(default=None, description="Commanded ADCS mode ")
    v_eci: Optional[AdcsXyzFloatT] = None
    qcf: Optional[AdcsQuatT] = None
    lease_time_remaining: Optional[StrictInt] = Field(default=None, description="time remaining in current ADCS lease ")
    unix_timestamp: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix epoch time ")
    omega_bi_est: Optional[AdcsXyzFloatT] = None
    control_error_omega: Optional[AdcsXyzFloatT] = None
    r_ecef: Optional[AdcsXyzFloatT] = None
    __properties: ClassVar[List[str]] = ["control_error_angle_deg", "acs_mode_active", "euler_angles", "control_error_q", "lat_deg", "q_bo_est", "latlontrack_lat", "lease_active", "lon_deg", "eclipse_flag", "q_bi_est", "latlontrack_lon", "r_eci", "altitude", "latlontrack_body_vector", "omega_bo_est", "acs_mode_cmd", "v_eci", "qcf", "lease_time_remaining", "unix_timestamp", "omega_bi_est", "control_error_omega", "r_ecef"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdcsHk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of euler_angles
        if self.euler_angles:
            _dict['euler_angles'] = self.euler_angles.to_dict()
        # override the default output from pydantic by calling `to_dict()` of control_error_q
        if self.control_error_q:
            _dict['control_error_q'] = self.control_error_q.to_dict()
        # override the default output from pydantic by calling `to_dict()` of q_bo_est
        if self.q_bo_est:
            _dict['q_bo_est'] = self.q_bo_est.to_dict()
        # override the default output from pydantic by calling `to_dict()` of q_bi_est
        if self.q_bi_est:
            _dict['q_bi_est'] = self.q_bi_est.to_dict()
        # override the default output from pydantic by calling `to_dict()` of r_eci
        if self.r_eci:
            _dict['r_eci'] = self.r_eci.to_dict()
        # override the default output from pydantic by calling `to_dict()` of latlontrack_body_vector
        if self.latlontrack_body_vector:
            _dict['latlontrack_body_vector'] = self.latlontrack_body_vector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of omega_bo_est
        if self.omega_bo_est:
            _dict['omega_bo_est'] = self.omega_bo_est.to_dict()
        # override the default output from pydantic by calling `to_dict()` of v_eci
        if self.v_eci:
            _dict['v_eci'] = self.v_eci.to_dict()
        # override the default output from pydantic by calling `to_dict()` of qcf
        if self.qcf:
            _dict['qcf'] = self.qcf.to_dict()
        # override the default output from pydantic by calling `to_dict()` of omega_bi_est
        if self.omega_bi_est:
            _dict['omega_bi_est'] = self.omega_bi_est.to_dict()
        # override the default output from pydantic by calling `to_dict()` of control_error_omega
        if self.control_error_omega:
            _dict['control_error_omega'] = self.control_error_omega.to_dict()
        # override the default output from pydantic by calling `to_dict()` of r_ecef
        if self.r_ecef:
            _dict['r_ecef'] = self.r_ecef.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdcsHk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "control_error_angle_deg": obj.get("control_error_angle_deg"),
            "acs_mode_active": obj.get("acs_mode_active"),
            "euler_angles": AdcsEulerT.from_dict(obj["euler_angles"]) if obj.get("euler_angles") is not None else None,
            "control_error_q": AdcsQuatT.from_dict(obj["control_error_q"]) if obj.get("control_error_q") is not None else None,
            "lat_deg": obj.get("lat_deg"),
            "q_bo_est": AdcsQuatT.from_dict(obj["q_bo_est"]) if obj.get("q_bo_est") is not None else None,
            "latlontrack_lat": obj.get("latlontrack_lat"),
            "lease_active": obj.get("lease_active"),
            "lon_deg": obj.get("lon_deg"),
            "eclipse_flag": obj.get("eclipse_flag"),
            "q_bi_est": AdcsQuatT.from_dict(obj["q_bi_est"]) if obj.get("q_bi_est") is not None else None,
            "latlontrack_lon": obj.get("latlontrack_lon"),
            "r_eci": AdcsXyzFloatT.from_dict(obj["r_eci"]) if obj.get("r_eci") is not None else None,
            "altitude": obj.get("altitude"),
            "latlontrack_body_vector": AdcsXyzFloatT.from_dict(obj["latlontrack_body_vector"]) if obj.get("latlontrack_body_vector") is not None else None,
            "omega_bo_est": AdcsXyzFloatT.from_dict(obj["omega_bo_est"]) if obj.get("omega_bo_est") is not None else None,
            "acs_mode_cmd": obj.get("acs_mode_cmd"),
            "v_eci": AdcsXyzFloatT.from_dict(obj["v_eci"]) if obj.get("v_eci") is not None else None,
            "qcf": AdcsQuatT.from_dict(obj["qcf"]) if obj.get("qcf") is not None else None,
            "lease_time_remaining": obj.get("lease_time_remaining"),
            "unix_timestamp": obj.get("unix_timestamp"),
            "omega_bi_est": AdcsXyzFloatT.from_dict(obj["omega_bi_est"]) if obj.get("omega_bi_est") is not None else None,
            "control_error_omega": AdcsXyzFloatT.from_dict(obj["control_error_omega"]) if obj.get("control_error_omega") is not None else None,
            "r_ecef": AdcsXyzFloatT.from_dict(obj["r_ecef"]) if obj.get("r_ecef") is not None else None
        })
        return _obj


