# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from oort_sdk_client.models.delivery_hints import DeliveryHints
from oort_sdk_client.models.ttl_params import TTLParams
from typing import Optional, Set
from typing_extensions import Self

class SendOptions(BaseModel):
    """
    options to apply to a send request
    """ # noqa: E501
    ttl_params: Optional[TTLParams] = Field(default=None, alias="TTLParams")
    reliable: Optional[StrictBool] = Field(default=True, description="whether to send an item reliably, i.e., with retries")
    tags: Optional[Dict[str, StrictStr]] = Field(default=None, description="a structure for optional file tags")
    delivery_hints: Optional[DeliveryHints] = None
    __properties: ClassVar[List[str]] = ["TTLParams", "reliable", "tags", "delivery_hints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ttl_params
        if self.ttl_params:
            _dict['TTLParams'] = self.ttl_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of delivery_hints
        if self.delivery_hints:
            _dict['delivery_hints'] = self.delivery_hints.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "TTLParams": TTLParams.from_dict(obj["TTLParams"]) if obj.get("TTLParams") is not None else None,
            "reliable": obj.get("reliable") if obj.get("reliable") is not None else True,
            "tags": obj.get("tags"),
            "delivery_hints": DeliveryHints.from_dict(obj["delivery_hints"]) if obj.get("delivery_hints") is not None else None
        })
        return _obj


