# coding: utf-8

"""
    OORT Agent SDK Interface

    Client interface to the OORT agent.

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from oort_sdk_client.models.send_options import SendOptions
from typing import Optional, Set
from typing_extensions import Self

class SendFileRequest(BaseModel):
    """
    SendFileRequest
    """ # noqa: E501
    destination: StrictStr = Field(description="the destination to send the file to")
    filepath: Annotated[str, Field(strict=True)] = Field(description="The source filepath.  Must be an absolute path.")
    topic: StrictStr = Field(description="the pipeline topic to send the file to")
    options: Optional[SendOptions] = None
    __properties: ClassVar[List[str]] = ["destination", "filepath", "topic", "options"]

    @field_validator('filepath')
    def filepath_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\/.*", value):
            raise ValueError(r"must validate the regular expression /^\/.*/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendFileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendFileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destination": obj.get("destination"),
            "filepath": obj.get("filepath"),
            "topic": obj.get("topic"),
            "options": SendOptions.from_dict(obj["options"]) if obj.get("options") is not None else None
        })
        return _obj


